-- MySQL Script generated by MySQL Workbench
-- mer. 28 avril 2021 11:51:45 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mars_odyssey
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mars_odyssey
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS mars_odyssey DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE mars_odyssey ;

-- -----------------------------------------------------
-- Table mars_odyssey.message
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mars_odyssey.message (
  id INT NOT NULL AUTO_INCREMENT,
  firstname VARCHAR(55) NOT NULL,
  message VARCHAR(255) NOT NULL,
  PRIMARY KEY (id))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;